version: "3"

networks:
        web:
                external: true
        #internal: 
        #       external: false
        #       driver: bridge

services:
        traefik:
                image: traefik:maroilles-alpine
                restart: unless-stop
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /data/traefik/traefik.toml:/traefik.toml
                        - /data/traefik/acme.json:/acme.json
                labels:
                        - traefik.backend=traefik
                        - traefik.frontend.rule=Host:monitor.alvarez.cuicas.pro
                        - traefik.port=8080
                networks:
                        - web


